import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from './Header.js'
import Footer from './Footer.js'
import { ToastContainer } from 'react-toastify'

const Layout = ({ title, children}) => {
    return (
        <>
            <Head>
                <title>{ title ? title + ' - My Shop ' : ' My Shop'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ToastContainer position='bottom-center' limit={1}></ToastContainer>

            <div className={styles.main}>
                <header><Header /></header>
                <main className={styles.children}>{children}</main>
                <footer><Footer /></footer>
            </div>
        </>
    )
}

export default Layout